markdown: kramdown
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
title: PolyU Robotics
baseurl: /polyu-robotics-club
github:
  another_url: https://github.com/PolyU-Robocon
